[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.bcmath",
  "php83Extensions.intl",
  "php83Extensions.pdo",
  "php83Extensions.mbstring",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "php83Extensions.openssl"
]

[phases.build]
cmds = [
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"